// src/genres.js

export const ncsGenres = [
    { value: "all", label: "🌍 Tous les genres" },
    { value: "31", label: "Alternative Dance" },
    { value: "32", label: "Alternative Hip-Hop" },
    { value: "33", label: "Alternative Pop" },
    { value: "23", label: "Ambient" },
    { value: "34", label: "Anti-Pop" },
    { value: "1", label: "Bass" },
    { value: "18", label: "Bass House" },
    { value: "78", label: "Bass Music" },
    { value: "26", label: "Brazilian Phonk" },
    { value: "27", label: "Breakbeat" },
    { value: "2", label: "Chill" },
    { value: "24", label: "Chill Bass" },
    { value: "35", label: "Chill Pop" },
    { value: "85", label: "Colour Bass" },
    { value: "65", label: "Complextro" },
    { value: "36", label: "Dance-Pop" },
    { value: "66", label: "Deep House" },
    { value: "45", label: "Disco" },
    { value: "46", label: "Disco House" },
    { value: "3", label: "Drum & Bass" },
    { value: "4", label: "Drumstep" },
    { value: "5", label: "Dubstep" },
    { value: "6", label: "EDM" },
    { value: "47", label: "Electro" },
    { value: "48", label: "Electro House" },
    { value: "7", label: "Electronic" },
    { value: "39", label: "Electronic Pop" },
    { value: "83", label: "Electronic Rock" },
    { value: "17", label: "Future Bass" },
    { value: "68", label: 'Future Bounce' },
    { value: "50", label: "Future Funk" },
    { value: "8", label: "Future House" },
    { value: "69", label: "Future Rave" },
    { value: "57", label: "Future Trap" },
    { value: "40", label: "Futurepop" },
    { value: "51", label: "Garage" },
    { value: "15", label: "Glitch Hop" },
    { value: "82", label: "Hardcore" },
    { value: "9", label: "Hardstyle" },
    { value: "10", label: "House" },
    { value: "41", label: "Hyperpop" },
    { value: "11", label: "Indie Dance" },
    { value: "91", label: "J-Pop" },
    { value: "84", label: "Jersey Club" },
    { value: "28", label: "Jump-Up" },
    { value: "29", label: "Liquid DnB" },
    { value: "60", label: "Lofi Hip-Hop" },
    { value: "12", label: "Melodic Dubstep" },
    { value: "54", label: "Melodic House" },
    { value: "22", label: "Midtempo Bass" },
    { value: "30", label: "Neurofunk" },
    { value: "87", label: "Nu-Jazz" },
    { value: "16", label: "Phonk" },
    { value: "86", label: "Pluggnb" },
    { value: "19", label: "Pop" },
    { value: "55", label: "Progressive House" },
    { value: "88", label: "RnB" },
    { value: "89", label: "Speed Garage" },
    { value: "73", label: "Tech House" },
    { value: "80", label: "Techno" },
    { value: "81", label: "Trance" },
    { value: "14", label: "Trap" },
    { value: "74", label: "Tribal House" },
    { value: "21", label: "UKG" },
    { value: "92", label: "Wave" },
    { value: "90", label: "Witch House" }
];